//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHSEC_G.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MHSEC_G.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] egg_dummy_template {
            get {
                object obj = ResourceManager.GetObject("egg_dummy_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] egg_null_template {
            get {
                object obj = ResourceManager.GetObject("egg_null_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001	Empty Slot
        ///0002	Locked Slot
        ///0003	Aptonoth Gene
        ///0004	Popo Gene
        ///0005	Apceros Gene
        ///0006	Yian Kut-Ku Gene
        ///0007	B. Yian Kut-Kue GeneASD
        ///0008	Gypceros Gene
        ///0009	P. Gypceros Gene
        ///000A	Yian Garuga Gene
        ///000B	Arzuros Gene
        ///000C	Lagombi Gene
        ///000D	Velocidrome Gene
        ///000E	Iodrome Gene
        ///000F	Gendrome Gene
        ///0010	Bulldrome Gene
        ///0011	Zamtrios Gene
        ///0012	Khezu Gene
        ///0013	Red Khezu Gene
        ///0014	Tigrex Gene
        ///0015	Brute Tigrex Gene
        ///0016	Nargacuga Gene
        ///0017	G. Nargacuga Gene
        ///0018	Rathian Gene
        ///0019	Pink Rathian  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gene {
            get {
                return ResourceManager.GetString("gene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001	Empty Slot
        ///0002	Locked Slot
        ///0003	アプトノス遺伝子
        ///0004	ポポ遺伝子
        ///0005	アプケロス遺伝子
        ///0006	怪鳥遺伝子
        ///0007	青怪鳥遺伝子
        ///0008	毒怪鳥遺伝子
        ///0009	紫毒怪鳥遺伝子
        ///000A	黒狼鳥遺伝子
        ///000B	青熊獣遺伝子
        ///000C	白兔獣遺伝子
        ///000D	ドスランポス遺伝子
        ///000E	ドスイーオス遺伝子
        ///000F	ドスゲネポス遺伝子
        ///0010	大猪遺伝子
        ///0011	化け鮫遺伝子
        ///0012	フルフル遺伝子
        ///0013	フルフル亜種遺伝子
        ///0014	轟竜遺伝子
        ///0015	黒轟竜遺伝子
        ///0016	迅竜遺伝子
        ///0017	緑迅竜遺伝子
        ///0018	雌火竜遺伝子
        ///0019	桜火竜遺伝子
        ///001A	金火竜遺伝子
        ///001B	火竜遺伝子
        ///001C	蒼火竜遺伝子
        ///001D	銀火竜遺伝子
        ///001E	隻眼の火竜遺伝子
        ///001F	角竜遺伝子
        ///0020	黒角竜遺伝子
        ///0021	一角竜遺伝子
        ///0022	白一角竜遺伝子
        ///0023	岩竜遺伝子
        ///0024	桃岩竜遺伝子
        ///0025	鎧竜遺伝子
        ///0026	黒鎧竜遺伝 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gene_JPN {
            get {
                return ResourceManager.GetString("gene_JPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10	1	Herb
        ///18	2	Potion
        ///20	3	Mega Potion
        ///28	4	Lifesoot
        ///30	5	Lifepowder
        ///38	6	Dust of Life
        ///40	7	Max Potion
        ///48	16	Vital Essence
        ///50	9	Immunizer
        ///58	8	Ancient Potion
        ///60	A	Antidote herb
        ///68	B	Antidote
        ///70	C	Aloe Leaf
        ///78	D	Burn Ointment
        ///80	E	Anesfreesia
        ///88	F	Anti-para Potion
        ///90	10	Hot Pepper
        ///98	11	Energy Drink
        ///A0	12	Girthy Garlic
        ///A8	13	Zest Pill
        ///B0	14	Soapgrass
        ///B8	15	Blast-Be-Gone
        ///C0	18	Manyberry
        ///C8	19	Eye Drops
        ///D0	1A	Nullberry ElixIr
        ///D8	AE	Burnt Meat
        ///E0	AF	Rare Steak
        ///E8	B0	Well-done Steak
        ///F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string idmap {
            get {
                return ResourceManager.GetString("idmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70	1	Herb
        ///78	2	Potion
        ///80	3	Mega Potion
        ///88	4	Lifesoot
        ///90	5	Lifepowder
        ///98	6	Dust of Life
        ///A0	7	Max Potion
        ///A8	16	Vital Essence
        ///B0	9	Immunizer
        ///B8	8	Ancient Potion
        ///C0	A	Antidote herb
        ///C8	B	Antidote
        ///D0	C	Aloe Leaf
        ///D8	D	Burn Ointment
        ///E0	E	Anesfreesia
        ///E8	F	Anti-para Potion
        ///F0	10	Hot Pepper
        ///F8	11	Energy Drink
        ///100	12	Girthy Garlic
        ///108	13	Zest Pill
        ///110	14	Soapgrass
        ///118	15	Blast-Be-Gone
        ///120	18	Manyberry
        ///128	19	Eye Drops
        ///130	1A	Nullberry ElixIr
        ///138	AE	Burnt Meat
        ///140	AF	Rare Steak
        ///148	B0	Well-don [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string idmapdroid {
            get {
                return ResourceManager.GetString("idmapdroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] monster_null_template_ANDROID {
            get {
                object obj = ResourceManager.GetObject("monster_null_template_ANDROID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] monster_null_template_JPN {
            get {
                object obj = ResourceManager.GetObject("monster_null_template_JPN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] monster_null_template_NA {
            get {
                object obj = ResourceManager.GetObject("monster_null_template_NA", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
